name: Build Go
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.17', '1.16' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go get -u github.com/gobuffalo/packr/v2/packr2
    - run: packr2
    - run: go build -o ./bin/dexo-map
    - run: packr2 clean
